cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

orders/urls.py
from django.urls import path

from .views import OrderCreateView

app_name = "orders"

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="create"),
]

products/urls.py
from django.urls import path

from .views import ProductDetailView, ProductListView

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", ProductListView.as_view(), name="list_by_category"),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # django admin
    path('admin/', admin.site.urls),
    # user management
    path("accounts/", include("allauth.urls")),
    # local
    path("products/", include("products.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),
    path("payments/", include("payments.urls")),
    path("contact/", include("contact.urls")),
    path("", include("pages.urls", namespace="pages")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms
from django.conf import settings

PRODUCT_QUANTITY_CHOICES = [
    (i, str(i)) for i in range(1, settings.CART_ITEM_MAX_QUANTITY + 1)
]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        label="Quantidade", choices=PRODUCT_QUANTITY_CHOICES, coerce=int
    )
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from products.models import Product
from django.contrib.auth.decorators import login_required

from .cart import Cart
from .forms import CartAddProductForm


@login_required
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], override_quantity=cd["override"]
        )

    return redirect("cart:detail")


@login_required
@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:detail")


def cart_detail(request):
    cart = Cart(request)
    return render(request, "cart/cart_detail.html", {"cart": cart})

templates/cart/cart_detail.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %}Meu Carrinho{% endblock title %}

{% block content %}
    <!-- Page info -->
	<div class="page-top-info">
		<div class="container">
			<h4>Meu Carrinho</h4>
			<div class="site-pagination">
				<a href="">Início</a> /
				<a href="">Carrinho</a> /
			</div>
		</div>
	</div>
	<!-- Page info end -->


	<!-- cart section end -->
	<section class="cart-section spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">
					<div class="cart-table">
						<h3>Meu Carrinho</h3>

						<div class="cart-table-warp">
							{% if cart %}
							<table>
								<thead>
									<tr>
										<th class="product-th">Produto</th>
										<th class="quy-th">Quantidade</th>
										<th class="total-th">Preço</th>
									</tr>
								</thead>
								<tbody>
									{% for item in cart %}
										{% with product=item.product %}
										<tr>
											<td class="product-col">
												<img src="/media/{{product.image}}" alt="">
												<div class="pc-title">
													 <a target="_blank" class="text-decoration-none" href="{{ product.get_absolute_url }}">
														<h4>{{ product.name }}</h4>
														 <p>R$ {{ item.price }}</p>
													</a>
												</div>
											</td>
											<td class="quy-col">
												<div class="quantity">
													<form action="{% url 'cart:add' product.id %}" method="post">
														{% csrf_token %}
														<div class="form-row">
															<div class="col">
																{% render_field item.update_quantity_form.quantity class+="form-control" %}
															</div>
															<div class="col">
																<input class="btn btn-info" type="submit" value="Atualizar">
															</div>
														</div>
														{{ item.update_quantity_form.override }}
													</form>
												</div>
											</td>
											<td class="total-col">
												<div class="form-row">
													<div class="col">
														R$ {{ item.total_price }}
													</div>
													<div class="col">
														<form action="{% url 'cart:remove' product.id %}" method="post">
															{% csrf_token %}
															<input class="btn btn-danger" value="Remover" type="submit"/>
														</form>
													</div>
												</div>
											</td>
										</tr>
										{% endwith %}
									{% endfor %}
								</tbody>
							</table>
							{% else %}
							<p>O carrinho está vazio!</p>
							{% endif %}
						</div>

						<div class="total-cost">
							<h6>Total <span>R$ {{ cart.get_total_price }}</span></h6>
						</div>
					</div>
				</div>
				<div class="col-lg-4 card-right">
					<a class="site-btn {% if not cart %}disabled{% endif %}" href="{% url 'orders:create' %}">Finalizar Compra</a>
					<a href="{% url 'products:list' %}" class="site-btn sb-dark">Continue Comprando</a>
				</div>
			</div>
		</div>
	</section>
	<!-- cart section end -->

{% endblock content %}