cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

contact/urls.py
from django.urls import path

from .views import contact_page

app_name = "contact"

urlpatterns = [
    path("", contact_page, name="contact"),
]

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

products/urls.py
from django.urls import path

from .views import ProductDetailView, ProductListView

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", ProductListView.as_view(), name="list_by_category"),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # django admin
    path('admin/', admin.site.urls),
    # user management
    path("accounts/", include("allauth.urls")),
    # local
    path("products/", include("products.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),
    path("payments/", include("payments.urls")),
    path("contact/", include("contact.urls")),
    path("", include("pages.urls", namespace="pages")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from autoslug import AutoSlugField
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel


class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_available=True)


class Category(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:list_by_category", kwargs={"slug": self.slug})


class Product(TimeStampedModel):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_available = models.BooleanField(default=True)

    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"slug": self.slug})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="description" content=" Luyza Ana Store | Maquiagens e Acessórios">
	<meta name="keywords" content="Luyza Ana, Maquiagem, Acessórios, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="col-lg-2 text-center text-lg-left">
						<!-- logo -->
						<a href="{% url 'pages:home' %}" class="site-logo">
							<img src="{% static 'img/logo.png' %}" alt="" width="50%" height="">
						</a>
					</div>
					<div class="col-xl-6 col-lg-5">
						<form class="header-search-form">
							<input type="text" placeholder="Pesquisar na Luyza Ana ....">
							<button><i class="flaticon-search"></i></button>
						</form>
					</div>
					<div class="col-xl-4 col-lg-5 direita">
						<div class="user-panel">
                            {% if user.is_authenticated %}
                            <div class="up-item">
								<i class="flaticon-profile"></i>
								<div class="dropdown">
									<a >{{ user }}</a>
									<div class="dropdown-content">
										<a href="{% url 'account_logout' %}">Sair</a>
										{% if user.is_staff %}
										<a href="/admin">Administration</a>
										{% endif %}
									</div>
								</div>
							</div>

                            <div class="up-item">
								<div class="shopping-card">
									<i class="flaticon-bag"></i>
								</div>
								<a href="{% url 'cart:detail' %}">Meu Carrinho</a>
							</div>
                            {% else %}
                            <div class="up-item">
								<i class="flaticon-profile"></i>
								<a href="{% url 'account_login' %}">Entrar</a> ou <a href="{% url 'account_signup' %}">Criar Conta</a>
							</div>
                            {% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
		<nav class="main-navbar">
			<div class="container">
				<!-- menu -->
				<ul class="main-menu">
					<li><a href="{% url 'pages:home' %}">Início</a></li>
					<li><a href="{% url 'products:list' %}">Produtos</a></li>
					<li><a href="{% url 'contact:contact' %}">Contato</a></li>
				</ul>
			</div>
		</nav>
	</header>
	<!-- Header section end -->

    {% block content %}{% endblock %}

	<!-- Footer section -->
	<section class="footer-section">
		<div class="container">
			<div class="footer-logo text-center">
				<a href="{% url 'pages:home' %}"><img src="{% static 'img/logo-light.png' %}" alt=""></a>
			</div>
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget about-widget">
						<h2>Sobre Nós</h2>
						<p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam frin-gilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p>
						<img src="{% static 'img/cards.png' %}" alt="">
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget contact-widget">
						<h2>Contato</h2>
						<div class="con-info">
							<span>C.</span>
							<p>Luyza Ana Store </p>
						</div>
						<div class="con-info">
							<span>T.</span>
							<p>+55 019 9878 09477</p>
						</div>
						<div class="con-info">
							<span>E.</span>
							<p>luyzastore@gmail.com</p>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget contact-widget social-links">
						<h2>Mídias</h2>
						<ul>
							<li><a href="https://instagram.com/luyzaanastore?utm_medium=copy_link" class="instagram">
																							<i class="fa fa-instagram"></i><span>instagram</span></a></li>
								<li><a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a></li>
								<li><a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Footer section end -->



	<!--====== Javascripts & Jquery ======-->
	<script src="/static/js/jquery-3.2.1.min.js"></script>
	<script src="/static/js/bootstrap.min.js"></script>
	<script src="/static/js/jquery.slicknav.min.js"></script>
	<script src="/static/js/owl.carousel.min.js"></script>
	<script src="/static/js/jquery.nicescroll.min.js"></script>
	<script src="/static/js/jquery.zoom.min.js"></script>
	<script src="/static/js/jquery-ui.min.js"></script>
	<script src="/static/js/main.js"></script>
	{% block script %}
    {% endblock script %}

	</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Luyza Ana Store | Maquiagens e Acessórios{% endblock %}

{% block content %}
{% load static %}
    <!-- letest product section -->
	<section class="top-letest-product-section">
		<div class="container">
			<div class="section-title">
				<h2>ÚLTIMOS LANÇAMENTOS</h2>
			</div>
			<div class="product-slider owl-carousel">
				{% for product in product_list %}
				<div class="product-item">
					<div class="pi-pic">
						<a href="{{ product.get_absolute_url }}">
							{% if product.image %}
							<img src="/media/{{product.image}}" alt="">
							{% else %}
							<img src="{% static 'img/no_image.jpg' %}" alt="">
							{% endif %}
						</a>
					</div>
					<div class="pi-text">
						<a href="{{ product.get_absolute_url }}">
							<h6>R$ {{ product.price }}</h6>
							<p>{{ product.name }}</p>
						</a>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</section>
	<!-- letest product section end -->
{% endblock %}

templates/order_summary.html
<div class="card border-0 bg-light p-4">
    <h4>Resumo do Pedido</h4>
    <ul class="list-group list-group-flush">
        {% for item in items %}
        <li class="list-group-item bg-light">
            {{ item.quantity }}x {{ item.product.name }}
            <span class="float-right">R$ {{ item.total_price }}{{ item.get_total_price }}</span>
        </li>
        {% endfor %}
        <li class="font-weight-bold list-group-item bg-light">Total
            <span class="float-right">R$ {{ total_price }}</span>
        </li>
    </ul>
</div>

templates/pagination.html
<div>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Anterior</a>
    {% endif %}
    Página {{ page.number }} de {{ page.paginator.num_pages }}.
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Próxima</a>
    {% endif %}
</div>